version: "3.9"
services:
  server:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/Knives
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql:
        condition: service_healthy  
    networks:
      - my_network  
    restart: always

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: Knives
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - my_network  
    restart: always
    volumes:
    - mysql-data:/var/lib/mysql  # Монтируем volume для сохранения данных
    volumes:
    mysql-data:
    driver: local
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host", "mysql"]  
      interval: 10s
      retries: 5
      timeout: 5s

networks:
  my_network:
    driver: bridge
